CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE partners (
    partner_id integer GENERATED BY DEFAULT AS IDENTITY,
    partner_name character varying(200),
    partner_type character varying(50),
    role_type character varying(50),
    contact_name character varying(200),
    email character varying(200),
    phone character varying(50),
    region character varying(100),
    status character varying(50),
    start_date date,
    end_date date,
    notes text,
    CONSTRAINT "PK_partners" PRIMARY KEY (partner_id)
);

CREATE TABLE public_impact_snapshots (
    snapshot_id integer GENERATED BY DEFAULT AS IDENTITY,
    snapshot_date date,
    headline character varying(500),
    summary_text text,
    metric_payload_json text,
    is_published boolean NOT NULL,
    published_at date,
    CONSTRAINT "PK_public_impact_snapshots" PRIMARY KEY (snapshot_id)
);

CREATE TABLE safehouses (
    safehouse_id integer GENERATED BY DEFAULT AS IDENTITY,
    safehouse_code character varying(20),
    name character varying(200),
    region character varying(100),
    city character varying(100),
    province character varying(100),
    country character varying(100),
    open_date date,
    status character varying(50),
    capacity_girls integer,
    capacity_staff integer,
    current_occupancy integer,
    notes text,
    CONSTRAINT "PK_safehouses" PRIMARY KEY (safehouse_id)
);

CREATE TABLE social_media_posts (
    post_id integer GENERATED BY DEFAULT AS IDENTITY,
    platform character varying(50),
    platform_post_id character varying(200),
    post_url character varying(500),
    created_at timestamp with time zone,
    day_of_week character varying(20),
    post_hour integer,
    post_type character varying(100),
    media_type character varying(50),
    caption text,
    hashtags text,
    num_hashtags integer,
    mentions_count integer,
    has_call_to_action boolean NOT NULL,
    call_to_action_type character varying(100),
    content_topic character varying(100),
    sentiment_tone character varying(50),
    caption_length integer,
    features_resident_story boolean NOT NULL,
    campaign_name character varying(200),
    is_boosted boolean NOT NULL,
    boost_budget_php numeric(18,2),
    impressions integer,
    reach integer,
    likes integer,
    comments integer,
    shares integer,
    saves integer,
    click_throughs integer,
    video_views integer,
    engagement_rate double precision,
    profile_visits integer,
    donation_referrals integer,
    estimated_donation_value_php numeric(18,2),
    follower_count_at_post integer,
    watch_time_seconds double precision,
    avg_view_duration_seconds double precision,
    subscriber_count_at_post integer,
    forwards double precision,
    CONSTRAINT "PK_social_media_posts" PRIMARY KEY (post_id)
);

CREATE TABLE supporters (
    supporter_id integer GENERATED BY DEFAULT AS IDENTITY,
    supporter_type character varying(50),
    display_name character varying(200),
    organization_name character varying(200),
    first_name character varying(100),
    last_name character varying(100),
    relationship_type character varying(50),
    region character varying(100),
    country character varying(100),
    email character varying(200),
    phone character varying(50),
    status character varying(50),
    created_at timestamp with time zone,
    first_donation_date date,
    acquisition_channel character varying(100),
    CONSTRAINT "PK_supporters" PRIMARY KEY (supporter_id)
);

CREATE TABLE partner_assignments (
    assignment_id integer GENERATED BY DEFAULT AS IDENTITY,
    partner_id integer,
    safehouse_id integer,
    program_area character varying(100),
    assignment_start date,
    assignment_end date,
    responsibility_notes text,
    is_primary boolean NOT NULL,
    status character varying(50),
    CONSTRAINT "PK_partner_assignments" PRIMARY KEY (assignment_id),
    CONSTRAINT "FK_partner_assignments_partners_partner_id" FOREIGN KEY (partner_id) REFERENCES partners (partner_id),
    CONSTRAINT "FK_partner_assignments_safehouses_safehouse_id" FOREIGN KEY (safehouse_id) REFERENCES safehouses (safehouse_id)
);

CREATE TABLE residents (
    resident_id integer GENERATED BY DEFAULT AS IDENTITY,
    case_control_no character varying(50),
    internal_code character varying(50),
    safehouse_id integer,
    case_status character varying(50),
    sex character varying(10),
    date_of_birth date,
    birth_status character varying(50),
    place_of_birth character varying(200),
    religion character varying(100),
    case_category character varying(100),
    sub_cat_orphaned boolean NOT NULL,
    sub_cat_trafficked boolean NOT NULL,
    sub_cat_child_labor boolean NOT NULL,
    sub_cat_physical_abuse boolean NOT NULL,
    sub_cat_sexual_abuse boolean NOT NULL,
    sub_cat_osaec boolean NOT NULL,
    sub_cat_cicl boolean NOT NULL,
    sub_cat_at_risk boolean NOT NULL,
    sub_cat_street_child boolean NOT NULL,
    sub_cat_child_with_hiv boolean NOT NULL,
    is_pwd boolean NOT NULL,
    pwd_type character varying(100),
    has_special_needs boolean NOT NULL,
    special_needs_diagnosis character varying(200),
    family_is_4ps boolean NOT NULL,
    family_solo_parent boolean NOT NULL,
    family_indigenous boolean NOT NULL,
    family_parent_pwd boolean NOT NULL,
    family_informal_settler boolean NOT NULL,
    date_of_admission date,
    age_upon_admission character varying(50),
    present_age character varying(50),
    length_of_stay character varying(50),
    referral_source character varying(100),
    referring_agency_person character varying(200),
    date_colb_registered date,
    date_colb_obtained date,
    assigned_social_worker character varying(50),
    initial_case_assessment character varying(200),
    date_case_study_prepared date,
    reintegration_type character varying(100),
    reintegration_status character varying(50),
    initial_risk_level character varying(50),
    current_risk_level character varying(50),
    date_enrolled date,
    date_closed date,
    created_at timestamp with time zone,
    notes_restricted text,
    CONSTRAINT "PK_residents" PRIMARY KEY (resident_id),
    CONSTRAINT "FK_residents_safehouses_safehouse_id" FOREIGN KEY (safehouse_id) REFERENCES safehouses (safehouse_id) ON DELETE RESTRICT
);

CREATE TABLE safehouse_monthly_metrics (
    metric_id integer GENERATED BY DEFAULT AS IDENTITY,
    safehouse_id integer,
    month_start date,
    month_end date,
    active_residents integer,
    avg_education_progress double precision,
    avg_health_score double precision,
    process_recording_count integer,
    home_visitation_count integer,
    incident_count integer,
    notes text,
    CONSTRAINT "PK_safehouse_monthly_metrics" PRIMARY KEY (metric_id),
    CONSTRAINT "FK_safehouse_monthly_metrics_safehouses_safehouse_id" FOREIGN KEY (safehouse_id) REFERENCES safehouses (safehouse_id)
);

CREATE TABLE donations (
    donation_id integer GENERATED BY DEFAULT AS IDENTITY,
    supporter_id integer,
    donation_type character varying(50),
    donation_date date,
    is_recurring boolean NOT NULL,
    campaign_name character varying(200),
    channel_source character varying(100),
    currency_code character varying(10),
    amount numeric(18,2),
    estimated_value numeric(18,2),
    impact_unit character varying(100),
    notes text,
    referral_post_id character varying(100),
    CONSTRAINT "PK_donations" PRIMARY KEY (donation_id),
    CONSTRAINT "FK_donations_supporters_supporter_id" FOREIGN KEY (supporter_id) REFERENCES supporters (supporter_id) ON DELETE RESTRICT
);

CREATE TABLE education_records (
    education_record_id integer GENERATED BY DEFAULT AS IDENTITY,
    resident_id integer,
    record_date date,
    education_level character varying(100),
    school_name character varying(200),
    enrollment_status character varying(50),
    attendance_rate double precision,
    progress_percent double precision,
    completion_status character varying(50),
    notes text,
    CONSTRAINT "PK_education_records" PRIMARY KEY (education_record_id),
    CONSTRAINT "FK_education_records_residents_resident_id" FOREIGN KEY (resident_id) REFERENCES residents (resident_id)
);

CREATE TABLE health_wellbeing_records (
    health_record_id integer GENERATED BY DEFAULT AS IDENTITY,
    resident_id integer,
    record_date date,
    general_health_score double precision,
    nutrition_score double precision,
    sleep_quality_score double precision,
    energy_level_score double precision,
    height_cm double precision,
    weight_kg double precision,
    bmi double precision,
    medical_checkup_done boolean NOT NULL,
    dental_checkup_done boolean NOT NULL,
    psychological_checkup_done boolean NOT NULL,
    notes text,
    CONSTRAINT "PK_health_wellbeing_records" PRIMARY KEY (health_record_id),
    CONSTRAINT "FK_health_wellbeing_records_residents_resident_id" FOREIGN KEY (resident_id) REFERENCES residents (resident_id)
);

CREATE TABLE home_visitations (
    visitation_id integer GENERATED BY DEFAULT AS IDENTITY,
    resident_id integer,
    visit_date date,
    social_worker character varying(50),
    visit_type character varying(100),
    location_visited character varying(200),
    family_members_present character varying(500),
    purpose character varying(500),
    observations text,
    family_cooperation_level character varying(50),
    safety_concerns_noted boolean NOT NULL,
    follow_up_needed boolean NOT NULL,
    follow_up_notes text,
    visit_outcome character varying(100),
    CONSTRAINT "PK_home_visitations" PRIMARY KEY (visitation_id),
    CONSTRAINT "FK_home_visitations_residents_resident_id" FOREIGN KEY (resident_id) REFERENCES residents (resident_id)
);

CREATE TABLE incident_reports (
    incident_id integer GENERATED BY DEFAULT AS IDENTITY,
    resident_id integer,
    safehouse_id integer,
    incident_date date,
    incident_type character varying(100),
    severity character varying(50),
    description text,
    response_taken text,
    resolved boolean NOT NULL,
    resolution_date date,
    reported_by character varying(50),
    follow_up_required boolean NOT NULL,
    CONSTRAINT "PK_incident_reports" PRIMARY KEY (incident_id),
    CONSTRAINT "FK_incident_reports_residents_resident_id" FOREIGN KEY (resident_id) REFERENCES residents (resident_id),
    CONSTRAINT "FK_incident_reports_safehouses_safehouse_id" FOREIGN KEY (safehouse_id) REFERENCES safehouses (safehouse_id)
);

CREATE TABLE intervention_plans (
    plan_id integer GENERATED BY DEFAULT AS IDENTITY,
    resident_id integer,
    plan_category character varying(100),
    plan_description text,
    services_provided character varying(500),
    target_value double precision,
    target_date date,
    status character varying(50),
    case_conference_date date,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT "PK_intervention_plans" PRIMARY KEY (plan_id),
    CONSTRAINT "FK_intervention_plans_residents_resident_id" FOREIGN KEY (resident_id) REFERENCES residents (resident_id)
);

CREATE TABLE process_recordings (
    recording_id integer GENERATED BY DEFAULT AS IDENTITY,
    resident_id integer,
    session_date date,
    social_worker character varying(50),
    session_type character varying(50),
    session_duration_minutes integer,
    emotional_state_observed character varying(100),
    emotional_state_end character varying(100),
    session_narrative text,
    interventions_applied character varying(200),
    follow_up_actions text,
    progress_noted boolean NOT NULL,
    concerns_flagged boolean NOT NULL,
    referral_made boolean NOT NULL,
    notes_restricted text,
    CONSTRAINT "PK_process_recordings" PRIMARY KEY (recording_id),
    CONSTRAINT "FK_process_recordings_residents_resident_id" FOREIGN KEY (resident_id) REFERENCES residents (resident_id)
);

CREATE TABLE donation_allocations (
    allocation_id integer GENERATED BY DEFAULT AS IDENTITY,
    donation_id integer,
    safehouse_id integer,
    program_area character varying(100),
    amount_allocated numeric(18,2),
    allocation_date date,
    allocation_notes text,
    CONSTRAINT "PK_donation_allocations" PRIMARY KEY (allocation_id),
    CONSTRAINT "FK_donation_allocations_donations_donation_id" FOREIGN KEY (donation_id) REFERENCES donations (donation_id),
    CONSTRAINT "FK_donation_allocations_safehouses_safehouse_id" FOREIGN KEY (safehouse_id) REFERENCES safehouses (safehouse_id)
);

CREATE TABLE in_kind_donation_items (
    item_id integer GENERATED BY DEFAULT AS IDENTITY,
    donation_id integer,
    item_name character varying(200),
    item_category character varying(100),
    quantity integer,
    unit_of_measure character varying(50),
    estimated_unit_value numeric(18,2),
    intended_use character varying(200),
    received_condition character varying(50),
    CONSTRAINT "PK_in_kind_donation_items" PRIMARY KEY (item_id),
    CONSTRAINT "FK_in_kind_donation_items_donations_donation_id" FOREIGN KEY (donation_id) REFERENCES donations (donation_id)
);

CREATE INDEX "IX_donation_allocations_donation_id" ON donation_allocations (donation_id);

CREATE INDEX "IX_donation_allocations_safehouse_id" ON donation_allocations (safehouse_id);

CREATE INDEX "IX_donations_supporter_id" ON donations (supporter_id);

CREATE INDEX "IX_education_records_resident_id" ON education_records (resident_id);

CREATE INDEX "IX_health_wellbeing_records_resident_id" ON health_wellbeing_records (resident_id);

CREATE INDEX "IX_home_visitations_resident_id" ON home_visitations (resident_id);

CREATE INDEX "IX_in_kind_donation_items_donation_id" ON in_kind_donation_items (donation_id);

CREATE INDEX "IX_incident_reports_resident_id" ON incident_reports (resident_id);

CREATE INDEX "IX_incident_reports_safehouse_id" ON incident_reports (safehouse_id);

CREATE INDEX "IX_intervention_plans_resident_id" ON intervention_plans (resident_id);

CREATE INDEX "IX_partner_assignments_partner_id" ON partner_assignments (partner_id);

CREATE INDEX "IX_partner_assignments_safehouse_id" ON partner_assignments (safehouse_id);

CREATE INDEX "IX_process_recordings_resident_id" ON process_recordings (resident_id);

CREATE INDEX "IX_residents_safehouse_id" ON residents (safehouse_id);

CREATE INDEX "IX_safehouse_monthly_metrics_safehouse_id" ON safehouse_monthly_metrics (safehouse_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260406184630_InitialCreate', '10.0.5');

COMMIT;

